### ISSUE TITLE
"""Clustering transcripts with 100% identity.""" 

### ISSUE THREAD

**Issue by Erythroxylum** [listonlab/Hyb-Seq_protocol#1]
The run gets stuck on this step forever. I have run the script on Ubuntu 13.10 and OSX 10.7.5. 

I am using your sample dataset, genome.fasta and transcriptome.fasta, to test this pipeline. There appears to be a problem with cd-hit-est properly reading single_transcript_hits.fasta. cd-hit-est starts running and "compares sequences from 0 to 0" indefinitely, resulting in a rapidly growing and empty cluster_100_single_transcript_hits_log.txt file. The program does not get stuck, it just runs forever without doing any actual clustering of the sequences.

When I use this script with other .fasta files, it appears to work correctly. And I cannot seem to find any errors in the single_transcript_hits.fasta.

**Comment by kweitemier** [comment]
This seems to be an issue with CD-HIT v4.6 and above. Other CD-HIT users have experienced this issue and it has been reported to the CD-HIT developers. I didn't experience the problem with version 4.5.8.

Is this issue preventing you from analyzing your own data, or is it only with the example files?

Thanks for reporting this.

**Comment by Erythroxylum** [comment]
Hi Kevin Weitemier,

Thanks for the response. The thing is, the problem only exists for the
sample files provided. When trying other small .fasta files they finish
immediately. We are now trying to get through blat with our dataset, the
barley genome and transcriptome.

Mark Fishbein provided your manuscript to my advisor, Robie Mason-Gamer, at
the Univ of Illinois at Chicago. We are hopefully going to complete a
hyb-seq protocol as well. Your manuscript and code thus far have been
extremely useful, the Building_exon_probes.sh file is especially
well-written. So thank you for your work thus far. I will let you know what
is going on with our data a bit further downstream.

Best,

Dawson

**Comment by kweitemier** [comment]
A patched version of CD-HIT 4.6.1 has been added to this repository. It's probably only necessary for testing example datasets.
